[project]
name = "payment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jonco", email = "jonco5555@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.129.0",
    "httpx>=0.28.1",
    "py-ecc>=8.0.0",
    "pydantic>=2.12.5",
    "pyyaml>=6.0.3",
    "typer>=0.15.0",
    "uvicorn>=0.34.0",
]

[project.scripts]
payment = "payment.cli:app"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "respx>=0.22.0",
]
