system:
  public_key_path: config/system_public_key.bin
  servers: 5
  failures: 2
  clients: 5
  initial_balance: 100
  delta: 5.0
  demo_enabled: true

servers:
  - id: server-0
    address: http://localhost:8000
  - id: server-1
    address: http://localhost:8001
  - id: server-2
    address: http://localhost:8002
  - id: server-3
    address: http://localhost:8003
  - id: server-4
    address: http://localhost:8004
